* EMCuda - Introduction
Welcome to EMCuda. This software project is my very own derivation of the topic I dealt within my master thesis: *Whispering Gallery Mode Resonators*.
The goal of this project is to solve Maxwells Equations for a dielectric Resonator via a finite element approach. To achieve this goal modern programming techniques
solutions and environments  will be used. Such are:

- CUDA/C
- OpenGL
- NixOS
- Literate Programming

** CUDA/C
[[https://developer.nvidia.com/cuda-zone][CUDA(Compute Unified Device Architecture)]] let's one create a programming paradigm in which the strenghts of GPU(Graphical Processing Unit) are used
to tackle a certain computing problem. In this case maxwell equations are solved on a finite element grid via a graphics device, using the dedicated resources
a graphics card provides. In theory this computing approach should yield a much better performance in the time department compared to computing on CPU
architectures. The strenghts of CUDA is efficient unification of blocks and advanced parallelism of operations.

** OpenGL


** NixOS

** Literate Programming
